version: '3'
services:
  mysql:
    image: mysql:8.0.12
    ports:
      - "3333:3306"
    volumes:
      - ./tmp/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root}
      - MYSQL_DATABASE=dev
  web:
    build: .
    command: sh ./start_server.sh
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - mysql
